/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "PhaseVocoderMono.h"
#include "AudioTool.h"
#include <stdlib.h>
/* Header for class voice_PhaseVocoder */

#ifndef _Included_voice_PhaseVocoder
#define _Included_voice_PhaseVocoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     voice_PhaseVocoder
 * Method:    native_init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_voice_PhaseVocoder_native_1init
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     voice_PhaseVocoder
 * Method:    native_put
 * Signature: ([S[S)I
 */
JNIEXPORT jint JNICALL Java_voice_PhaseVocoder_native_1put___3S_3S
  (JNIEnv *, jobject, jshortArray, jshortArray);

/*
 * Class:     voice_PhaseVocoder
 * Method:    native_put
 * Signature: ([S)I
 */
JNIEXPORT jint JNICALL Java_voice_PhaseVocoder_native_1put___3S
  (JNIEnv *, jobject, jshortArray);

/*
 * Class:     voice_PhaseVocoder
 * Method:    native_get
 * Signature: ([S)I
 */
JNIEXPORT jint JNICALL Java_voice_PhaseVocoder_native_1get
  (JNIEnv *, jobject, jshortArray);

/*
 * Class:     voice_PhaseVocoder
 * Method:    native_reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_voice_PhaseVocoder_native_1reset
  (JNIEnv *, jobject);

/*
 * Class:     voice_PhaseVocoder
 * Method:    native_setPitchRate
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_voice_PhaseVocoder_native_1setPitchRate
  (JNIEnv *, jobject, jdouble);


#ifdef __cplusplus
}
#endif
#endif
