/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "AudioPlayer.h"
/* Header for class voice_OpenSLAudioPlayer */

#ifndef _Included_voice_OpenSLAudioPlayer
#define _Included_voice_OpenSLAudioPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     voice_OpenSLAudioPlayer
 * Method:    native_init
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_voice_OpenSLAudioPlayer_native_1init
  (JNIEnv *, jobject, jint, jint, jint);

JNIEXPORT void JNICALL Java_voice_OpenSLAudioPlayer_native_1uninit
  (JNIEnv *, jobject);
/*
 * Class:     voice_OpenSLAudioPlayer
 * Method:    native_start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_voice_OpenSLAudioPlayer_native_1start
  (JNIEnv *, jobject);

/*
 * Class:     voice_OpenSLAudioPlayer
 * Method:    native_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_voice_OpenSLAudioPlayer_native_1stop
  (JNIEnv *, jobject);

/*
 * Class:     voice_OpenSLAudioPlayer
 * Method:    native_put
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_voice_OpenSLAudioPlayer_native_1put
  (JNIEnv *, jobject, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
