/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "Encoder.h"
#include <stdlib.h>
/* Header for class voice_VoiceEncoder */

#ifndef _Included_voice_VoiceEncoder
#define _Included_voice_VoiceEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     voice_VoiceEncoder
 * Method:    native_init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_voice_VoiceEncoder_native_1init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     voice_VoiceEncoder
 * Method:    native_put
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_voice_VoiceEncoder_native_1put
  (JNIEnv *, jobject, jshortArray, jbyteArray);

/*
 * Class:     voice_VoiceEncoder
 * Method:    native_reset
 * Signature: ()Vfef
 */
JNIEXPORT void JNICALL Java_voice_VoiceEncoder_native_1reset
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
